### ISSUE TITLE
R2DOC & rJava version >1.7

### ISSUE THREAD

**Issue by jmichaelgilbert** [davidgohel/R2DOC#1]
Hi David,

Apologies if this is not the correct format (still learning GitHub and R), but I experienced an issue installing R2DOC in R this morning. I'm installing R2DOC since it's a dependency for R2DOCX. Specifically, when installing R2DOC the installation fails during "testing if installed package can be loaded" with the error:

```
Error : .onLoad failed in loadNamespace() for 'R2DOC', details:
  call: fun(libname, pkgname)
  error: R2DOC does not support java version 1.8.0_73. Expected version is 1.6 or 1.7
Error: loading failed
Execution halted
ERROR: loading failed
* removing 'C:/Program Files/R/R-3.2.3/library/R2DOC'
```

Any thoughts on how to remedy this? Is there a way to coerce R2DOC to accept the newer version of java?

Best,
Michael

**Comment by davidgohel** [comment]
Hi

Sorry, this package is no more supported since 2 years. You can migrate to ReporteRs instead. 

https://github.com/davidgohel/ReporteRs

David
